// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"VisitorCounter/internal/config"
	"VisitorCounter/internal/database"
	"VisitorCounter/internal/services"
)

// Injectors from wire.go:

// CreateApp initializes all dependencies
func CreateApp() (*services.VisitorService, error) {
	configConfig := config.NewConfig()
	db, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	visitorService := services.NewVisitorService(db)
	return visitorService, nil
}
